version: '3.0'

volumes:
  pgdata:

services:
  node-app: 
    container_name: node-app
    image: task-7
    build: 
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - own_network
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    restart: on-failure
    networks:
      - own_network

networks:
  own_network:
    driver: bridge
